<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>OpenTms.Platform</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Authorization" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Features" Version="10.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenTms.Platform.Domain.Shared\OpenTms.Platform.Domain.Shared.csproj" />
  </ItemGroup>

</Project>
